In [1]:
import os
import sys
import pandas as pd
import json
import ast

In [2]:
pd.set_option("display.max_columns", 150)
pd.set_option("display.max_rows", 150)

In [3]:
current_dir = os.getcwd()

# 프로젝트 루트 디렉토리 찾기 (notebooks/preprocessing에서 두 단계 위로 이동)
root_dir = os.path.abspath(os.path.join(current_dir, "..", ".."))
print(f"프로젝트 루트 디렉토리: {root_dir}")
sys.path.append(root_dir)

프로젝트 루트 디렉토리: /Users/hazel/Documents/map-search-agent

In [ ]:
data_root = os.path.join(root_dir, 'prod_info_0219.json')
data_root

'/Users/hazel/Documents/map-search-agent/prod_info_0219.json'

In [7]:
with open(data_root, 'r') as file:
    meta_data = json.load(file)

meta_data = pd.json_normalize(meta_data)

In [8]:
meta_data.shape

(125, 102)

In [10]:
meta_data.head(1)

,pmProductID,providingKind.nonDiyVsDiy.value,voice.includedVoiceCall.value,voice.includedVideoOrValueAddedCall.value,voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange,voice.includedVoiceCallTospecifiedNumbers.voiceCallRange,smsText.includedText.value,smsText.includedTextSeparateSetting.textRange,includedData.value,additionalDataUsage.includedDataForSharingAndTethering.value,additionalDataUsage.includedMVoIP.value,additionalDataUsage.includedDataSeparateSetting.dataRange,dataQoS.appliedSpeed.value,seniorDataExceedLimit.availableToApply.value,generalDataExceedLimit.availableToApply.value,monthlyPrice.monthlyPrice.value,monthlyPrice.monthlyPriceWithoutVAT.value,monthlyPrice.monthlyPriceWithSelectableInstallment.value,monthlyPrice.billingMethod.value,optionData.dataOptionProvidingMethod,deductibleInfo.deductibilityForDisability.value,benefitOfVoiceCall.performRefill.voiceCallRefillRange,benefitOfData.dataOptionRefill.dataRefillAmount.value,benefitOfData.dataOptionRefill.dataRefillCouponGiftingAvailability.value,benefitOfData.dataOptionGift.maximumShareAmount.value,benefitOfData.dataOptionGiftReceiving.dataGiftReceivingAvailability.value,managementInfo.productId.value,managementInfo.statusOfOperation.value,managementInfo.classifiedGroup.value,managementInfo.productName.value,managementInfo.productNameInEnglish.value,managementInfo.lineup.value,managementInfo.marketingKeyword.valueList,managementInfo.generation.valueList,managementInfo.approvalInfo.value,managementInfo.productOperationPeriod.value,managementInfo.mappedProductCode.productCode.valueList,managementInfo.versionInfo.value,managementInfo.productDescription.value,managementInfo.productSubscriptionCondition.value,managementInfo.productSubscriptionMethod.value,salesInfo.netPrice.value,topupInfo.reChargeAvailability.availability.value,processInfo.onboardingDevice.deviceType.eligibility,processInfo.onboardingDevice.deviceType.valueList,processInfo.onboardingServiceCode.eligibility,processInfo.onboardingServiceCode.valueList,customerInfo.onboardingCustomer.ageRule,otherOnboardInfo.productChangeLineup.availability.value,otherOnboardInfo.directPlanOnboard.value,otherOnboardInfo.fixedPlanContractConcurrentSignupRestriction.value,otherOnboardInfo.tsupportFundOnboard.value,productRelation.signupPreTermination.productInformation.productList,productRelation.signupPreTermination.productInformation.groupList,productRelation.signupConcurrentTermination.productInformation.productList,productRelation.signupConcurrentTermination.productInformation.groupList,productRelation.terminationPreTermination.productInformation.productList,productRelation.terminationPreTermination.productInformation.groupList,productRelation.terminationConcurrentTermination.productInformation.productList,productRelation.terminationConcurrentTermination.productInformation.groupList,productRelation.subRule.productInformation.productList,productRelation.subRule.productInformation.groupList,campaignRelation.signupPreTermination.campaignInformationDTO.campaignList,campaignRelation.signupConcurrentTermination.campaignInformationDTO.campaignList,campaignRelation.terminationPreTermination.campaignInformationDTO.campaignList,campaignRelation.terminationConcurrentTermination.campaignInformationDTO.campaignList,commonRule.lineSuspensionCondition.value,commonRule.planChangeCondition.dailyPlanChangeLimit.value,commonRule.planChangeCondition.monthlyPlanChangeLimit.value,productBenefitConditions.allOfferBenefits,productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList,productBenefitConditions.optionalOfferBenefits.mutuallyExclusiveBenefits,optionData.optionDataName.value,optionData.selectionMethod.value,optionData.totalNumOfOptions.value,optionData.minNumOfOptionSelectable.value,optionData.maxNumOfOptionSelectable.value,deductibleInfo.additionalOfferForDisabilities.value,campaignRelation.signupConcurrentSignup.campaignInformationDTO.campaignList,productBenefitConditions.optionalOfferBenefits.selectableBenefitCount.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCountPeriodFrom.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCountPeriodTo.value,productBenefitConditions.optionalOfferBenefits.isAutoEnrollmentBenefitOnSignup.value,customerInfo.onboardingCustomer.customerTypeRule.eligibility,customerInfo.onboardingCustomer.customerTypeRule.valueList,customerInfo.onboardingCustomer.businessCustomerSubtypeRule.eligibility,customerInfo.onboardingCustomer.businessCustomerSubtypeRule.valueList,otherOnboardInfo.duplicateNameOnboard.domain.valueList,otherOnboardInfo.duplicateNameOnboard.productGroup.productInformation.groupList,autoProductChange.changeRule.dateBase.value,autoProductChange.changeRule.date.value,autoProductChange.productNameAfterChange.pmProductId,autoProductChange.productNameAfterChange.legacyProductId,autoProductChange.productNameAfterChange.productName,productBenefitConditions.optionalOfferBenefits.autoSelectedBenefit.productInformation.productList,managementInfo.productRequiredNotice.value,topupInfo.chargeAmount.minimumChargeAmount.value,topupInfo.chargeAmount.maximumChargeAmount.value,otherOnboardInfo.specialCustomerOnboard.isSoldier.value,otherOnboardInfo.duplicateNameOnboard.productGroup.eligibility,customerInfo.onboardingCustomer.individualCustomerSubtypeRule.eligibility,customerInfo.onboardingCustomer.individualCustomerSubtypeRule.valueList
0,PA00000001,Non DIY,무제한,300분,[],[],기본제공,[],15GB,15GB,15GB,[],1Mbps,N,N,38000원,34546원,38000원,후불,"[{'detailedDataOptionName': {}, 'providingData...",N,"[{'range': {'valueList': ['영상통화', '부가통화']}, 'r...",15GB,Y,2GB,Y,PA00000001,운영,상품 > 기본요금제 > 휴대폰 요금제,다이렉트5G 38,Direct5G 38,다이렉트플랜,"[유심개통, 쓰던폰, USIM개통, 비대면, 자급제, 온라인, 데이터100GB 이하...","[LTE generation, 5G generation]",요금팀/이현정,2021.01.14~9999.12.31,[NA00007164],1.0,월 15GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입...,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,"고객센터, 대리점, T월드 가입 가능",34545원,N,True,[스마트폰 단말기 유형],False,"[HDN, PPS국제수신, PPS, 택시공중전화개인용, 회사택시공중전화, 개인택시공...",[],N,Y,Y,Y,"[{'pmProductId': 'PD00000018', 'legacyProductI...",[],"[{'pmProductId': 'PB00001593', 'legacyProductI...","[{'groupName': 'ITM0000215', 'groupList': [{'p...","[{'pmProductId': 'PB00001253', 'legacyProductI...",[],"[{'pmProductId': 'PB00001250', 'legacyProductI...",[],[],[],"[{'pmCampaignId': 'BB00000001', 'campaignName'...","[{'pmCampaignId': 'BA00000031', 'campaignName'...","[{'pmCampaignId': 'BA00000028', 'campaignName'...","[{'pmCampaignId': 'BA00000047', 'campaignName'...",AC,5,1,[{'benefitInfo': {'productInformation': {'prod...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1. 불필요 컬럼 제거 
- 제거 기준 : 내용이 없는 경우(값이 하나 또는 전체 없음), 내용이 의미 없는 경우(상품 검색 차원에서 의미 없음)

In [ ]:
# 시트2에 있는 102개 필드 중 28개가 제외 대상
drop_cols = ['additionalDataUsage.includedDataSeparateSetting.dataRange',
'autoProductChange.changeRule.date.value',
'autoProductChange.changeRule.dateBase.value',
'autoProductChange.productNameAfterChange.legacyProductId',
'autoProductChange.productNameAfterChange.pmProductId',
'autoProductChange.productNameAfterChange.productName',
'campaignRelation.signupConcurrentSignup.campaignInformationDTO.campaignList',
'campaignRelation.signupConcurrentTermination.campaignInformationDTO.campaignList',
'campaignRelation.signupPreTermination.campaignInformationDTO.campaignList',
'campaignRelation.terminationConcurrentTermination.campaignInformationDTO.campaignList',
'campaignRelation.terminationPreTermination.campaignInformationDTO.campaignList',
'commonRule.lineSuspensionCondition.value',
'customerInfo.onboardingCustomer.businessCustomerSubtypeRule.eligibility',
'customerInfo.onboardingCustomer.businessCustomerSubtypeRule.valueList',
'managementInfo.approvalInfo.value',
'managementInfo.productOperationPeriod.value',
'managementInfo.productRequiredNotice.value',
'managementInfo.productSubscriptionMethod.value',
'managementInfo.versionInfo.value',
'otherOnboardInfo.duplicateNameOnboard.domain.valueList',
'otherOnboardInfo.productChangeLineup.availability.value',
'processInfo.onboardingDevice.deviceType.eligibility',
'processInfo.onboardingDevice.deviceType.valueList',
'processInfo.onboardingServiceCode.eligibility',
'processInfo.onboardingServiceCode.valueList',
'productRelation.subRule.productInformation.groupList',
'productRelation.subRule.productInformation.productList',
'providingKind.nonDiyVsDiy.value']

In [20]:
drop_columns = []
for col_nm in meta_data.columns:
    if col_nm in drop_cols:
        drop_columns.append(col_nm)
print(len(drop_columns))

28

In [21]:
try:
    meta_data.drop(columns=drop_columns, inplace=True)
except KeyError as e:
    print("존재하지 않는 컬럼을 무시하고 계속 진행합니다.")

In [ ]:
# 나머지 필드가 74개이면 됨 
meta_data.shape

(125, 74)

In [25]:
save_path = "valid_columns.txt"
valid_columns = pd.DataFrame([meta_data.columns])
valid_columns.to_csv(save_path, sep='\n', header=False, index=False, encoding='utf-8')

In [24]:
os.getcwd()

'/Users/hazel/Documents/map-search-agent/notebooks/preprocessing'

In [26]:
# 컬럼명 요약어로 변경
token_set  = set()
dup_set = set()

for field in meta_data.columns:
    field = field.replace('|', '.')
    field_parts = field.split('.')
    if field_parts[-1] in token_set:
        dup_set.add(field_parts[-1])
    token_set.add(field_parts[-1])

column_mapper = {}

for field in meta_data.columns:
    field = field.replace('|', '.')
    field_parts = field.split('.')
    top_filed = field_parts[0]

    if field_parts[-1] == 'value' or field_parts[-1] == 'valueList':
        if field_parts[-2] in dup_set:
            value = top_filed + '.' + '.'.join(field_parts[-2:-1])
            column_mapper[field] = value
        else:
            if len(field_parts) > 1:
                value = top_filed + '.' + field_parts[-2]
                column_mapper[field] = value
            else:
                value = field_parts[-2]
                column_mapper[field] = value
    else:
        if field_parts[-1] in dup_set:
            value = top_filed + '.' + '.'.join(field_parts[-2:])
            column_mapper[field] = value
        else:
            if len(field_parts) > 1:
                value = top_filed + '.' + field_parts[-1]
                column_mapper[field] = value
            else:
                value = field_parts[-1]
                column_mapper[field] = value


# column mapper[dict] -> json으로 저장      

filename = 'column_mapper.json'

if not os.path.exists(filename):
    with open(filename, 'w') as json_file:
        json.dump(column_mapper, json_file, indent=4)
    print(f"파일 '{filename}'이 저장되었습니다.")
else:
    print(f"파일 '{filename}'이 이미 존재합니다.")

파일 'column_mapper.json'이 저장되었습니다.

In [27]:
not_matched_columns = []
for column in meta_data.columns:
    try:
        column_mapper[column]
    except KeyError as e:
        not_matched_columns.append(column)

not_matched_columns

[]

## 2. PREPROCESSING

In [144]:
renamed_valid_meta = meta_data.copy()

In [145]:
renamed_valid_meta.head(3)

,pmProductID,voice.includedVoiceCall.value,voice.includedVideoOrValueAddedCall.value,voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange,voice.includedVoiceCallTospecifiedNumbers.voiceCallRange,smsText.includedText.value,smsText.includedTextSeparateSetting.textRange,includedData.value,additionalDataUsage.includedDataForSharingAndTethering.value,additionalDataUsage.includedMVoIP.value,dataQoS.appliedSpeed.value,seniorDataExceedLimit.availableToApply.value,generalDataExceedLimit.availableToApply.value,monthlyPrice.monthlyPrice.value,monthlyPrice.monthlyPriceWithoutVAT.value,monthlyPrice.monthlyPriceWithSelectableInstallment.value,monthlyPrice.billingMethod.value,optionData.dataOptionProvidingMethod,deductibleInfo.deductibilityForDisability.value,benefitOfVoiceCall.performRefill.voiceCallRefillRange,benefitOfData.dataOptionRefill.dataRefillAmount.value,benefitOfData.dataOptionRefill.dataRefillCouponGiftingAvailability.value,benefitOfData.dataOptionGift.maximumShareAmount.value,benefitOfData.dataOptionGiftReceiving.dataGiftReceivingAvailability.value,managementInfo.productId.value,managementInfo.statusOfOperation.value,managementInfo.classifiedGroup.value,managementInfo.productName.value,managementInfo.productNameInEnglish.value,managementInfo.lineup.value,managementInfo.marketingKeyword.valueList,managementInfo.generation.valueList,managementInfo.mappedProductCode.productCode.valueList,managementInfo.productDescription.value,managementInfo.productSubscriptionCondition.value,salesInfo.netPrice.value,topupInfo.reChargeAvailability.availability.value,customerInfo.onboardingCustomer.ageRule,otherOnboardInfo.directPlanOnboard.value,otherOnboardInfo.fixedPlanContractConcurrentSignupRestriction.value,otherOnboardInfo.tsupportFundOnboard.value,productRelation.signupPreTermination.productInformation.productList,productRelation.signupPreTermination.productInformation.groupList,productRelation.signupConcurrentTermination.productInformation.productList,productRelation.signupConcurrentTermination.productInformation.groupList,productRelation.terminationPreTermination.productInformation.productList,productRelation.terminationPreTermination.productInformation.groupList,productRelation.terminationConcurrentTermination.productInformation.productList,productRelation.terminationConcurrentTermination.productInformation.groupList,commonRule.planChangeCondition.dailyPlanChangeLimit.value,commonRule.planChangeCondition.monthlyPlanChangeLimit.value,productBenefitConditions.allOfferBenefits,productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList,productBenefitConditions.optionalOfferBenefits.mutuallyExclusiveBenefits,optionData.optionDataName.value,optionData.selectionMethod.value,optionData.totalNumOfOptions.value,optionData.minNumOfOptionSelectable.value,optionData.maxNumOfOptionSelectable.value,deductibleInfo.additionalOfferForDisabilities.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCount.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCountPeriodFrom.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCountPeriodTo.value,productBenefitConditions.optionalOfferBenefits.isAutoEnrollmentBenefitOnSignup.value,customerInfo.onboardingCustomer.customerTypeRule.eligibility,customerInfo.onboardingCustomer.customerTypeRule.valueList,otherOnboardInfo.duplicateNameOnboard.productGroup.productInformation.groupList,productBenefitConditions.optionalOfferBenefits.autoSelectedBenefit.productInformation.productList,topupInfo.chargeAmount.minimumChargeAmount.value,topupInfo.chargeAmount.maximumChargeAmount.value,otherOnboardInfo.specialCustomerOnboard.isSoldier.value,otherOnboardInfo.duplicateNameOnboard.productGroup.eligibility,customerInfo.onboardingCustomer.individualCustomerSubtypeRule.eligibility,customerInfo.onboardingCustomer.individualCustomerSubtypeRule.valueList
0,PA00000001,무제한,300분,[],[],기본제공,[],15GB,15GB,15GB,1Mbps,N,N,38000원,34546원,38000원,후불,"[{'detailedDataOptionName': {}, 'providingData...",N,"[{'range': {'valueList': ['영상통화', '부가통화']}, 'r...",15GB,Y,2GB,Y,PA00000001,운영,상품 > 기본요금제 > 휴대폰 요금제,다이렉트5G 38,Direct5G 38,다이렉트플랜,"[유심개통, 쓰던폰, USIM개통, 비대면, 자급제, 온라인, 데이터100GB 이하...","[LTE generation, 5G generation]",[NA00007164],월 15GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입...,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,34545원,N,[],Y,Y,Y,"[{'pmProductId': 'PD00000018', 'legacyProductI...",[],"[{'pmProductId': 'PB00001593', 'legacyProductI...","[{'groupName': 'ITM0000215', 'groupList': [{'p...","[{'pmProductId': 'PB00001253', 'legacyProductI...",[],"[{'pmProductId': 'PB00001250', 'legacyProductI...",[],5,1,[{'benefitInfo': {'productInformation': {'prod...,[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PA00000002,무제한,100분,[],[],기본제공,[],1.8GB,1.8GB,1.8GB,NaN,N,Y,22000원,20000원,22000원,후불,[{'detailedDataOptionName': {'value': '심야데이터 7...,Y,"[{'range': {'valueList': ['영상통화', '부가통화']}, 'r...",1.8GB,Y,2GB,Y,PA00000002,운영,상품 > 기본요금제 > 휴대폰 요금제,다이렉트LTE 22,DirectLTE 22,LTE 다이렉트플랜,"[자급제, 비대면, 온라인, 티다샵, 티다이렉트샵, 유심개통, USIM개통, 쓰던폰...","[LTE generation, 5G generation]",[NA00007166],월 1.8GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가...,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,20000원,N,[],Y,Y,Y,"[{'pmProductId': 'PA00000219', 'legacyProductI...",[],"[{'pmProductId': 'PB00001592', 'legacyProductI...","[{'groupName': 'ITM0000215', 'groupList': [{'p...","[{'pmProductId': 'PB00001253', 'legacyProductI...",[],"[{'pmProductId': 'PB00001433', 'legacyProductI...",[],5,1,NaN,[],[],심야데이터 할인,포함 옵션,1,1,1,200분,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PA00000003,무제한,300분,[],[],기본제공,[],5GB,5GB,5GB,1Mbps,N,N,35000원,31819원,35000원,후불,[{'detailedDataOptionName': {'value': '심야데이터 7...,N,"[{'range': {'valueList': ['영상통화', '부가통화']}, 'r...",5GB,Y,2GB,Y,PA00000003,운영,상품 > 기본요금제 > 휴대폰 요금제,다이렉트LTE 35,DirectLTE 35,LTE 다이렉트플랜,"[쓰던폰, 자급제, 비대면, 온라인, 티다이렉트샵, 유심개통, USIM개통, 심야데...","[LTE generation, 5G generation]",[NA00007167],월 5GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입 ...,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,31818원,N,[],Y,Y,Y,"[{'pmProductId': 'PA00000219', 'legacyProductI...",[],"[{'pmProductId': 'PB00001593', 'legacyProductI...","[{'groupName': 'ITM0000215', 'groupList': [{'p...","[{'pmProductId': 'PB00000251', 'legacyProductI...",[],"[{'pmProductId': 'PB00001254', 'legacyProductI...",[],5,1,NaN,[],[],심야데이터 할인,포함 옵션,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2-1) 여러 정보를 포함하는 필드를 분리 저장 
- benefitOfVoiceCall.performRefill.voiceCallRefillRange
- voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange
- voice.includedVoiceCallTospecifiedNumbers.voiceCallRange

In [147]:
#renamed_valid_meta.iloc[28]["benefitOfVoiceCall.performRefill.voiceCallRefillRange"]
def extract_refill_amount(data):
    """
    benefitOfVoiceCall.performRefill.voiceCallRefillRange 데이터에서 refillAmount 값을 추출
    데이터 예시: [
        {
            'range': {'valueList': ['망내통화', '망외통화', '부가통화', '유선통화']},
            'refillAmount': {'value': '20%'}
        }
    ]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 refillAmount 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'refillAmount' in first_item:
            refill_amount_obj = first_item['refillAmount']
            if isinstance(refill_amount_obj, dict) and 'value' in refill_amount_obj:
                return refill_amount_obj['value']
    
    return None

def extract_range_value_list(data):
    """
    benefitOfVoiceCall.performRefill.voiceCallRefillRange 데이터에서 range의 valueList를 추출
    데이터 예시: [
        {
            'range': {'valueList': ['망내통화', '망외통화', '부가통화', '유선통화']},
            'refillAmount': {'value': '20%'}
        }
    ]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 range의 valueList 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'range' in first_item:
            range_obj = first_item['range']
            if isinstance(range_obj, dict) and 'valueList' in range_obj:
                return range_obj['valueList']
    
    return None

In [148]:
renamed_valid_meta['benefitOfVoiceCall.performRefill.voiceCallRefillRange.refillAmount'] = renamed_valid_meta['benefitOfVoiceCall.performRefill.voiceCallRefillRange'].apply(extract_refill_amount)
renamed_valid_meta['benefitOfVoiceCall.performRefill.voiceCallRefillRange.range'] = renamed_valid_meta['benefitOfVoiceCall.performRefill.voiceCallRefillRange'].apply(extract_range_value_list)

In [149]:
# 전처리끝나면 drop
renamed_valid_meta.drop(columns="benefitOfVoiceCall.performRefill.voiceCallRefillRange", inplace=True)

In [150]:
def extract_providing_amount(data):
    """
    voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange 데이터에서 providingAmount 값을 추출
    데이터 예시: [
        {
            'range': {'valueList': ['망내통화', '망외통화', '부가통화', '유선통화']},
            'providingAmount': {'value': '60분'}
        }
    ]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 refillAmount 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'providingAmount' in first_item:
            refill_amount_obj = first_item['providingAmount']
            if isinstance(refill_amount_obj, dict) and 'value' in refill_amount_obj:
                return refill_amount_obj['value']
    
    return None

def extract_range_value_list(data):
    """
    renamed_valid_meta["voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange"].iloc[28]
    voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange 데이터에서 providingAmount 값을 추출
    데이터 예시: [
        {
            'range': {'valueList': ['망내통화', '망외통화', '부가통화', '유선통화']},
            'providingAmount': {'value': '60분'}
        }
    ]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 range의 valueList 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'range' in first_item:
            range_obj = first_item['range']
            if isinstance(range_obj, dict) and 'valueList' in range_obj:
                return range_obj['valueList']
    
    return None

In [151]:
renamed_valid_meta['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.providingAmount'] = renamed_valid_meta['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange'].apply(extract_providing_amount)
renamed_valid_meta['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.range'] = renamed_valid_meta['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange'].apply(extract_range_value_list)

In [152]:
renamed_valid_meta.drop(columns="voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange", inplace=True)

In [153]:
def extract_providing_amount(data):
    """
    voice.includedVoiceCallTospecifiedNumbers.voiceCallRange 데이터에서 providingAmount 값을 추출
    데이터 예시: [
        [{'range': {'valueList': ['망내통화']},
        'providingAmount': {'value': '무제한'},
        'numberOfService': {'value': '2'}}]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 refillAmount 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'providingAmount' in first_item:
            refill_amount_obj = first_item['providingAmount']
            if isinstance(refill_amount_obj, dict) and 'value' in refill_amount_obj:
                return refill_amount_obj['value']
    
    return None

def extract_range_value_list(data):
    """
    voice.includedVoiceCallTospecifiedNumbers.voiceCallRange 데이터에서 providingAmount 값을 추출
    데이터 예시: [
        [{'range': {'valueList': ['망내통화']},
        'providingAmount': {'value': '무제한'},
        'numberOfService': {'value': '2'}}]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 range의 valueList 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'range' in first_item:
            range_obj = first_item['range']
            if isinstance(range_obj, dict) and 'valueList' in range_obj:
                return range_obj['valueList']
    
    return None

def extract_numberOfService(data):
    """
        voice.includedVoiceCallTospecifiedNumbers.voiceCallRange 데이터에서 providingAmount 값을 추출
        데이터 예시: [
            [{'range': {'valueList': ['망내통화']},
            'providingAmount': {'value': '무제한'},
            'numberOfService': {'value': '2'}}]
    """
    if isinstance(data, str):
        try:
            # 문자열인 경우 리스트로 변환
            data = ast.literal_eval(data)
        except:
            return None
    
    if isinstance(data, list) and len(data) > 0:
        # 리스트의 첫 번째 항목에서 range의 valueList 추출
        first_item = data[0]
        if isinstance(first_item, dict) and 'numberOfService' in first_item:
            range_obj = first_item['numberOfService']
            if isinstance(range_obj, dict) and 'value' in range_obj:
                return range_obj['value']
    
    return None

In [154]:
renamed_valid_meta['voice.includedVoiceCallTospecifiedNumbers.voiceCallRange.providingAmount'] = renamed_valid_meta['voice.includedVoiceCallTospecifiedNumbers.voiceCallRange'].apply(extract_providing_amount)
renamed_valid_meta['voice.includedVoiceCallTospecifiedNumbers.voiceCallRange.range'] = renamed_valid_meta['voice.includedVoiceCallTospecifiedNumbers.voiceCallRange'].apply(extract_range_value_list)
renamed_valid_meta['voice.includedVoiceCallTospecifiedNumbers.voiceCallRange.numberOfService'] = renamed_valid_meta['voice.includedVoiceCallTospecifiedNumbers.voiceCallRange'].apply(extract_numberOfService)

In [155]:
renamed_valid_meta.drop(columns="voice.includedVoiceCallTospecifiedNumbers.voiceCallRange", inplace=True)

### 2-2) 음성 통화량 관련 필드 병합

In [ ]:
# 음성통화 제공량 관련해서는 '망내, 망외' 같은 정보 제외하고 제공 시간 정보와 특정 번호 관련 제공량만 남김
- 특정 번호에 대해서는 망내 무제한인걸 기본 상식으로 description 등에 적어두고, 망내/망외 이런 것들 정보는 제거

In [ ]:
# 필드 병합
renamed_valid_meta.loc[~renamed_valid_meta['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.providingAmount'].isnull(), 'voice.includedVoiceCall.value'] = renamed_valid_meta[~renamed_valid_meta['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.providingAmount'].isnull()]['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.providingAmount']

In [ ]:
# 불필요 필드 제거
renamed_valid_meta.drop(columns = ['voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.providingAmount', 'voice.includedVoiceCallVideoOrValueAddedCallSeparateSetting.voiceCallRange.range', 'voice.includedVoiceCallTospecifiedNumbers.voiceCallRange.providingAmount', 'voice.includedVoiceCallTospecifiedNumbers.voiceCallRange.range'], inplace=True)

### 2-3) 혜택 정보 단순화
- 깊은 depth로 여러 정보가 제공되던 것에서, 혜택으로 제공하는 상품명만 추출
- productBenefitConditions.allOfferBenefits.benefitInfo
- productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList
- optionData.dataOptionProvidingMethod

In [ ]:
productBenefit_df = renamed_valid_meta[["pmProductID", "productBenefitConditions.allOfferBenefits"]]

from typing import Union
import ast

def extract_val(data, keys: Union[str, list]):
    """재귀적으로 중첩된 딕셔너리에서 값을 추출"""
    if data is None:
        return None
        
    if isinstance(keys, str):
        try:
            return data.get(keys) if isinstance(data, dict) else None
        except:
            return None
        
    elif isinstance(keys, list) and len(keys) > 0:
        if len(keys) == 1:
            return data.get(keys[0]) if isinstance(data, dict) else None
        else:
            # 첫 번째 키로 값을 가져온 후 나머지 키들로 재귀 호출
            first_key = keys[0]
            remaining_keys = keys[1:]
            next_data = data.get(first_key) if isinstance(data, dict) else None
            return extract_val(next_data, remaining_keys)
    else:
        return None


def parse_allOffer(data):
    """
        [
            {
            'benefitInfo': 
                {
                'productInformation': {
                    'productList': [
                        {
                            'pmProductId': 'BA00000047',
                            'productName': 'Wavve 2천원 할인'
                        }
                        ]   
                    }
                },
            'benefitPeriodTo': {'value': '9999.12.31'},
            'benefitAutoEnrollment': {'isBenefitAutoEnrollment': {'value': 'Y'},
            'benefitAutoEnrollmentReferenceTime': {'value': '혜택 적용 상품 가입시'}},
            'benefitAutoCancellation': {'isBenefitAutoCancellation': {'value': 'Y'},
            'benefitAutoTerminationReferenceTime': {'value': '혜택 적용 상품 해지시'}}}
        ]
    """

    def parse(list_data: list) -> list:
        """ 초기 버젼에서는 product_id, product_name 만 추출"""
        result_data = [] 
        for item in list_data:
            benefitPeriodTo = extract_val(item, keys=['benefitPeriodTo'])
            benefitAutoEnrollment = extract_val(item, keys=['benefitAutoEnrollment'])
            benefitAutoEnrollmentReferenceTime = extract_val(item, keys=['benefitAutoEnrollmentReferenceTime'])
            benefitAutoCancellation = extract_val(item, keys=['benefitAutoCancellation'])
            benefitAutoTerminationReferenceTime = extract_val(item, keys=['benefitAutoTerminationReferenceTime'])
            product_list = extract_val(item, keys=['benefitInfo', 'productInformation', 'productList'])
            if product_list:
                for product in product_list:
                    product_id = product['pmProductId']
                    product_name = product['productName']
                    result_data.append(
                        {
                            "productId": product_id,
                            "productName": product_name,
                        }
                    )
        if not result_data:
            return None
        
        return result_data

    if isinstance(data, dict):
        data = parse([data])

    elif isinstance(data, list):
        data = parse(data)
    else:
        try:
            data = ast.literal_eval(data)
            data = parse(data)
        except:
            return None

    return data

# 디버깅을 위한 테스트 함수
def debug_parse_allOffer(data, index=None):
    """디버깅용 함수"""
    print(f"디버깅 - 인덱스: {index}")
    print(f"데이터 타입: {type(data)}")
    print(f"데이터 내용: {data}")
    
    result = parse_allOffer(data)
    print(f"파싱 결과: {result}")
    print("-" * 50)
    return result

# 적용
#productBenefit_df.loc[:, 'productBenefitConditions.allOfferBenefits.benefitInfo'] = productBenefit_df['productBenefitConditions.allOfferBenefits'].apply(parse_allOffer)

#디버깅이 필요한 경우 아래 코드 사용
for idx in range(min(5, len(productBenefit_df))):  # 처음 5개 행만 디버깅
    debug_parse_allOffer(productBenefit_df.iloc[idx]['productBenefitConditions.allOfferBenefits'], idx)

디버깅 - 인덱스: 0
데이터 타입: <class 'list'>
데이터 내용: [{'benefitInfo': {'productInformation': {'productList': [{'pmProductId': 'BA00000047', 'productName': 'Wavve 2천원 할인'}]}}, 'benefitPeriodTo': {'value': '9999.12.31'}, 'benefitAutoEnrollment': {'isBenefitAutoEnrollment': {'value': 'Y'}, 'benefitAutoEnrollmentReferenceTime': {'value': '혜택 적용 상품 가입시'}}, 'benefitAutoCancellation': {'isBenefitAutoCancellation': {'value': 'Y'}, 'benefitAutoTerminationReferenceTime': {'value': '혜택 적용 상품 해지시'}}}]
파싱 결과: [{'productId': 'BA00000047', 'productName': 'Wavve 2천원 할인'}]
--------------------------------------------------
디버깅 - 인덱스: 1
데이터 타입: <class 'float'>
데이터 내용: nan
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 2
데이터 타입: <class 'float'>
데이터 내용: nan
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 3
데이터 타입: <class 'float'>
데이터 내용: nan
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 4
데이터 타입: <class 'list'>
데이터 내용: [{'benefitInfo': {'productInformation': {'productList': [{'pmProductId': 'BA00000047', 'productName': 'Wavve 2천원 할인'}]}}, 'benefitPeriodTo': {'value': '9999.12.31'}, 'benefitAutoEnrollment': {'isBenefitAutoEnrollment': {'value': 'Y'}, 'benefitAutoEnrollmentReferenceTime': {'value': '혜택 적용 상품 가입시'}}, 'benefitAutoCancellation': {'isBenefitAutoCancellation': {'value': 'Y'}, 'benefitAutoTerminationReferenceTime': {'value': '혜택 적용 상품 해지시'}}}]
파싱 결과: [{'productId': 'BA00000047', 'productName': 'Wavve 2천원 할인'}]
--------------------------------------------------

In [164]:
renamed_valid_meta.loc[:, 'productBenefitConditions.allOfferBenefits.benefitInfo'] = renamed_valid_meta['productBenefitConditions.allOfferBenefits'].apply(parse_allOffer)

In [165]:
def extract_val(data, keys: Union[str, list]):
    """재귀적으로 중첩된 딕셔너리에서 값을 추출"""
    if data is None:
        return None
        
    if isinstance(keys, str):
        try:
            return data.get(keys) if isinstance(data, dict) else None
        except:
            return None
        
    elif isinstance(keys, list) and len(keys) > 0:
        if len(keys) == 1:
            return data.get(keys[0]) if isinstance(data, dict) else None
        else:
            # 첫 번째 키로 값을 가져온 후 나머지 키들로 재귀 호출
            first_key = keys[0]
            remaining_keys = keys[1:]
            next_data = data.get(first_key) if isinstance(data, dict) else None
            return extract_val(next_data, remaining_keys)
    else:
        return None

def parse_Offer(data):
    """
    productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList 데이터를 파싱하여 pmProductId, productName정보를 추출
    sampleData: productOptionalBenefit_df.iloc[9]["productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList"][0]
    {   'benefitInfo': {'productInformation': {'productList': [{'pmProductId': 'BA00000038',
        'productName': 'FLO 무료'}]}},
        'benefitPeriodTo': {'value': '9999.12.31'},
        'benefitChangeReferenceDate': {'value': '직전 혜택 변경일'},
        'benefitChangeAvailableDate': {'value': '즉시'}
    }
    """

    def parse(list_data: list) -> list:
        """ 초기 버젼에서는 product_id, product_name 만 추출"""
        result_data = [] 
        for item in list_data:
            product_list = extract_val(item, keys=['benefitInfo', 'productInformation', 'productList'])
            if product_list:
                for product in product_list:
                    product_id = product['pmProductId']
                    product_name = product['productName']
                    result_data.append(
                        {
                            "productId": product_id,
                            "productName": product_name,
                        }
                    )
        if not result_data:
            return None
        
        return result_data

    if isinstance(data, dict):
        data = parse([data])

    elif isinstance(data, list):
        data = parse(data)
    else:
        try:
            data = ast.literal_eval(data)
            data = parse(data)
        except:
            return None

    return data


# 디버깅을 위한 테스트 함수
def debug_parse_allOffer(data, index=None):
    """디버깅용 함수"""
    print(f"디버깅 - 인덱스: {index}")
    print(f"데이터 타입: {type(data)}")
    print(f"데이터 내용: {data}")
    
    result = parse_allOffer(data)
    print(f"파싱 결과: {result}")
    print("-" * 50)
    return result

#디버깅이 필요한 경우 아래 코드 사용
for idx in range(min(20, len(productOptionalBenefit_df))):  # 처음 5개 행만 디버깅
    debug_parse_allOffer(productOptionalBenefit_df.iloc[idx]['productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList'], idx)

디버깅 - 인덱스: 0
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 1
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 2
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 3
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 4
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 5
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 6
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 7
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 8
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 9
데이터 타입: <class 'list'>
데이터 내용: [{'productId': 'BA00000038', 'productName': 'FLO 무료'}, {'productId': 'BA00000041', 'productName': 'Wavve 무료'}, {'productId': 'BA00001857', 'productName': '우주패스 편의점&카페 할인'}, {'productId': 'BA00001871', 'productName': 'T우주패스 쇼핑(11번가/G마켓) 제공'}]
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 10
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 11
데이터 타입: <class 'list'>
데이터 내용: [{'productId': 'BA00000039', 'productName': 'FLO 할인'}, {'productId': 'BA00000042', 'productName': 'Wavve 할인'}, {'productId': 'BA00001857', 'productName': '우주패스 편의점&카페 할인'}, {'productId': 'BA00001871', 'productName': 'T우주패스 쇼핑(11번가/G마켓) 제공'}]
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 12
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 13
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 14
데이터 타입: <class 'list'>
데이터 내용: [{'productId': 'BA00000037', 'productName': 'T멤버십 VIP'}, {'productId': 'BA00001870', 'productName': 'Wavve & FLO 동시할인'}]
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 15
데이터 타입: <class 'list'>
데이터 내용: [{'productId': 'BA00000039', 'productName': 'FLO 할인'}, {'productId': 'BA00000042', 'productName': 'Wavve 할인'}, {'productId': 'BA00001872', 'productName': 'T우주패스 쇼핑 제공(FLO 또는 Wavve 옵션 선택 필요)'}, {'productId': 'BA00001874', 'productName': 'T우주패스 편의점&카페 할인(FLO 또는 Wavve 옵션 선택 필요)'}]
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 16
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 17
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 18
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------
디버깅 - 인덱스: 19
데이터 타입: <class 'NoneType'>
데이터 내용: None
파싱 결과: None
--------------------------------------------------

In [168]:
renamed_valid_meta.loc[:, 'productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList'] = renamed_valid_meta['productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList'].apply(parse_Offer)

In [169]:
renamed_valid_meta.drop(columns = ['productBenefitConditions.allOfferBenefits'], inplace = True)

In [171]:
def extract_val(data, keys: Union[str, list]):
    """재귀적으로 중첩된 딕셔너리에서 값을 추출"""
    if data is None:
        return None
        
    if isinstance(keys, str):
        try:
            return data.get(keys) if isinstance(data, dict) else None
        except:
            return None
        
    elif isinstance(keys, list) and len(keys) > 0:
        if len(keys) == 1:
            return data.get(keys[0]) if isinstance(data, dict) else None
        else:
            # 첫 번째 키로 값을 가져온 후 나머지 키들로 재귀 호출
            first_key = keys[0]
            remaining_keys = keys[1:]
            next_data = data.get(first_key) if isinstance(data, dict) else None
            return extract_val(next_data, remaining_keys)
    else:
        return None

def parse_field(data):
    """
    optionData.iloc[1]["optionData.dataOptionProvidingMethod"] 파싱하여 detailedDataOptionName, legacyDataOptionCode
    sampleData: optionData.iloc[1]["optionData.dataOptionProvidingMethod"]
    [
        {
            'detailedDataOptionName': {'value': '베이직 플러스 데이터 충전 75GB'},
            'providingDataOptionMethod': {'value': '데이터 추가'},
            'legacyDataOptionCode': {'value': 'NA00008243'},
            'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {'value': '75GB'},
            'dataQoSAfterUsedUp': {'value': 'QOS 적용 없음'}},
            'frequencyOfApplyingDataOption': {'frequency': {'value': '매월'}},
            'timePeriodForApplyingDataOption': {'timePeriod': {'value': '적용 없음'}},
            'dataOptionApplyLocation': {'value': '전 지역'},
            'dataOptionMonthlyPrice': {'value': '9000원'}}
        },
    ]
    """

    def parse(list_data: list) -> list:
        """ 초기 버젼에서는 product_id, product_name 만 추출"""
        result_data = [] 
        for item in list_data:
            name = extract_val(item, keys=['detailedDataOptionName', 'value'])
            id = extract_val(item, keys=['legacyDataOptionCode', 'value'])
            dataOptionProvidingRecord = extract_val(item, keys=['dataOptionProvidingRecord', 'dataOptionExtraData', 'dataAmount', 'value'])
            dataSubtractionDiscountRate = extract_val(item, keys=['dataOptionProvidingRecord', 'dataSubtractionDiscountRate', 'rateDiscount', 'value'])
            monthlyPrice = extract_val(item, keys=['dataOptionProvidingRecord','dataOptionMonthlyPrice', 'value'])
            result_data.append(
                {
                    "productId": id,
                    "productName": name,
                    "extradataAmount": dataOptionProvidingRecord,
                    "monthlyPrice": monthlyPrice,
                    "DiscountRate": dataSubtractionDiscountRate
                }
            )
        if not result_data:
            return None
        
        return result_data

    if isinstance(data, dict):
        data = parse([data])

    elif isinstance(data, list):
        data = parse(data)
    else:
        try:
            data = ast.literal_eval(data)
            data = parse(data)
        except:
            return None

    return data


# 디버깅을 위한 테스트 함수
def debug_parse(data, index=None):
    """디버깅용 함수"""
    print(f"디버깅 - 인덱스: {index}")
    print(f"데이터 타입: {type(data)}")
    print(f"데이터 내용: {data}")
    
    result = parse_field(data)
    print(f"파싱 결과: {result}")
    print("-" * 50)
    return result

#디버깅이 필요한 경우 아래 코드 사용
for idx in range(min(60, len(renamed_valid_meta))):  # 처음 5개 행만 디버깅
    debug_parse(renamed_valid_meta.iloc[idx]['optionData.dataOptionProvidingMethod'], idx)

디버깅 - 인덱스: 0
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 1
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {'value': '심야데이터 75% 할인'}, 'providingDataOptionMethod': {'value': '데이터 차감율 할인'}, 'dataOptionProvidingRecord': {'dataSubtractionDiscountRate': {'rateDiscount': {'value': '75%'}}, 'frequencyOfApplyingDataOption': {'frequency': {'value': '매일'}}, 'timePeriodForApplyingDataOption': {'timePeriod': {'value': '00:00-07:00'}}, 'dataOptionApplyLocation': {'value': '전 지역'}, 'dataOptionMonthlyPrice': {'value': '무료'}}}]
파싱 결과: [{'productId': None, 'productName': '심야데이터 75% 할인', 'extradataAmount': None, 'monthlyPrice': '무료', 'DiscountRate': '75%'}]
--------------------------------------------------
디버깅 - 인덱스: 2
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {'value': '심야데이터 75% 할인'}, 'providingDataOptionMethod': {'value': '데이터 차감율 할인'}, 'dataOptionProvidingRecord': {'dataSubtractionDiscountRate': {'rateDiscount': {'value': '75%'}}, 'frequencyOfApplyingDataOption': {'frequency': {'value': '매일'}}, 'timePeriodForApplyingDataOption': {'timePeriod': {'value': '00:00-07:00'}}, 'dataOptionApplyLocation': {'value': '전 지역'}, 'dataOptionMonthlyPrice': {'value': '무료'}}}]
파싱 결과: [{'productId': None, 'productName': '심야데이터 75% 할인', 'extradataAmount': None, 'monthlyPrice': '무료', 'DiscountRate': '75%'}]
--------------------------------------------------
디버깅 - 인덱스: 3
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 4
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 5
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 6
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 7
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 8
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 9
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 10
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {'value': '심야데이터 75% 할인'}, 'providingDataOptionMethod': {'value': '데이터 차감율 할인'}, 'dataOptionProvidingRecord': {'dataSubtractionDiscountRate': {'rateDiscount': {'value': '75%'}}, 'frequencyOfApplyingDataOption': {'frequency': {'value': '매일'}}, 'timePeriodForApplyingDataOption': {'timePeriod': {'value': '00:00-07:00'}}, 'dataOptionApplyLocation': {'value': '전 지역'}, 'dataOptionMonthlyPrice': {'value': '무료'}}}]
파싱 결과: [{'productId': None, 'productName': '심야데이터 75% 할인', 'extradataAmount': None, 'monthlyPrice': '무료', 'DiscountRate': '75%'}]
--------------------------------------------------
디버깅 - 인덱스: 11
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 12
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 13
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 14
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 15
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 16
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 17
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 18
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 19
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 20
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 21
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 22
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 23
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 24
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 25
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 26
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {}, 'providingDataOptionMethod': {}, 'detailedDataOptionId': {}, 'legacyDataOptionCode': {}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {}, 'dataQoSAfterUsedUp': {}}, 'qosAfterIncludedDataConsumed': {'dataQoSAfterUsedUp': {}}, 'dataSubtractionDiscountRate': {'rateDiscount': {}}, 'frequencyOfApplyingDataOption': {'frequency': {}}, 'timePeriodForApplyingDataOption': {'timePeriod': {}}, 'dataOptionApplyLocation': {}, 'dataOptionMonthlyPrice': {}}}]
파싱 결과: [{'productId': None, 'productName': None, 'extradataAmount': None, 'monthlyPrice': None, 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 27
데이터 타입: <class 'list'>
데이터 내용: [{'detailedDataOptionName': {'value': '매일 2GB+3Mbps 데이터 추가'}, 'providingDataOptionMethod': {'value': '데이터 추가'}, 'legacyDataOptionCode': {'value': '-'}, 'dataOptionProvidingRecord': {'dataOptionExtraData': {'dataAmount': {'value': '2GB'}, 'dataQoSAfterUsedUp': {'value': '3Mbps'}}, 'frequencyOfApplyingDataOption': {'frequency': {'value': '매일'}}, 'timePeriodForApplyingDataOption': {'timePeriod': {'value': '적용 없음'}}, 'dataOptionApplyLocation': {'value': '전 지역'}, 'dataOptionMonthlyPrice': {'value': '무료'}}}]
파싱 결과: [{'productId': '-', 'productName': '매일 2GB+3Mbps 데이터 추가', 'extradataAmount': '2GB', 'monthlyPrice': '무료', 'DiscountRate': None}]
--------------------------------------------------
디버깅 - 인덱스: 28
데이터 타입: <class 'list'>

In [175]:
renamed_valid_meta.loc[:, 'optionData.dataOptionProvidingMethod'] = renamed_valid_meta['optionData.dataOptionProvidingMethod'].apply(parse_field)

In [177]:
renamed_valid_meta.head(1)

,pmProductID,voice.includedVoiceCall.value,voice.includedVideoOrValueAddedCall.value,smsText.includedText.value,smsText.includedTextSeparateSetting.textRange,includedData.value,additionalDataUsage.includedDataForSharingAndTethering.value,additionalDataUsage.includedMVoIP.value,dataQoS.appliedSpeed.value,seniorDataExceedLimit.availableToApply.value,generalDataExceedLimit.availableToApply.value,monthlyPrice.monthlyPrice.value,monthlyPrice.monthlyPriceWithoutVAT.value,monthlyPrice.monthlyPriceWithSelectableInstallment.value,monthlyPrice.billingMethod.value,optionData.dataOptionProvidingMethod,deductibleInfo.deductibilityForDisability.value,benefitOfData.dataOptionRefill.dataRefillAmount.value,benefitOfData.dataOptionRefill.dataRefillCouponGiftingAvailability.value,benefitOfData.dataOptionGift.maximumShareAmount.value,benefitOfData.dataOptionGiftReceiving.dataGiftReceivingAvailability.value,managementInfo.productId.value,managementInfo.statusOfOperation.value,managementInfo.classifiedGroup.value,managementInfo.productName.value,managementInfo.productNameInEnglish.value,managementInfo.lineup.value,managementInfo.marketingKeyword.valueList,managementInfo.generation.valueList,managementInfo.mappedProductCode.productCode.valueList,managementInfo.productDescription.value,managementInfo.productSubscriptionCondition.value,salesInfo.netPrice.value,topupInfo.reChargeAvailability.availability.value,customerInfo.onboardingCustomer.ageRule,otherOnboardInfo.directPlanOnboard.value,otherOnboardInfo.fixedPlanContractConcurrentSignupRestriction.value,otherOnboardInfo.tsupportFundOnboard.value,productRelation.signupPreTermination.productInformation.productList,productRelation.signupPreTermination.productInformation.groupList,productRelation.signupConcurrentTermination.productInformation.productList,productRelation.signupConcurrentTermination.productInformation.groupList,productRelation.terminationPreTermination.productInformation.productList,productRelation.terminationPreTermination.productInformation.groupList,productRelation.terminationConcurrentTermination.productInformation.productList,productRelation.terminationConcurrentTermination.productInformation.groupList,commonRule.planChangeCondition.dailyPlanChangeLimit.value,commonRule.planChangeCondition.monthlyPlanChangeLimit.value,productBenefitConditions.optionalOfferBenefits.optionalOfferBenefitDetailList,productBenefitConditions.optionalOfferBenefits.mutuallyExclusiveBenefits,optionData.optionDataName.value,optionData.selectionMethod.value,optionData.totalNumOfOptions.value,optionData.minNumOfOptionSelectable.value,optionData.maxNumOfOptionSelectable.value,deductibleInfo.additionalOfferForDisabilities.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCount.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCountPeriodFrom.value,productBenefitConditions.optionalOfferBenefits.selectableBenefitCountPeriodTo.value,productBenefitConditions.optionalOfferBenefits.isAutoEnrollmentBenefitOnSignup.value,customerInfo.onboardingCustomer.customerTypeRule.eligibility,customerInfo.onboardingCustomer.customerTypeRule.valueList,otherOnboardInfo.duplicateNameOnboard.productGroup.productInformation.groupList,productBenefitConditions.optionalOfferBenefits.autoSelectedBenefit.productInformation.productList,topupInfo.chargeAmount.minimumChargeAmount.value,topupInfo.chargeAmount.maximumChargeAmount.value,otherOnboardInfo.specialCustomerOnboard.isSoldier.value,otherOnboardInfo.duplicateNameOnboard.productGroup.eligibility,customerInfo.onboardingCustomer.individualCustomerSubtypeRule.eligibility,customerInfo.onboardingCustomer.individualCustomerSubtypeRule.valueList,benefitOfVoiceCall.performRefill.voiceCallRefillRange.refillAmount,benefitOfVoiceCall.performRefill.voiceCallRefillRange.range,voice.includedVoiceCallTospecifiedNumbers.voiceCallRange.numberOfService,productBenefitConditions.allOfferBenefits.benefitInfo
0,PA00000001,무제한,300분,기본제공,[],15GB,15GB,15GB,1Mbps,N,N,38000원,34546원,38000원,후불,"[{'productId': None, 'productName': None, 'ext...",N,15GB,Y,2GB,Y,PA00000001,운영,상품 > 기본요금제 > 휴대폰 요금제,다이렉트5G 38,Direct5G 38,다이렉트플랜,"[유심개통, 쓰던폰, USIM개통, 비대면, 자급제, 온라인, 데이터100GB 이하...","[LTE generation, 5G generation]",[NA00007164],월 15GB 데이터를 제공하는 SK텔레콤 공식 온라인 채널인 T다이렉트샵에서만 가입...,T다이렉트샵(SK텔레콤 공식온라인채널)을 통하여 신규/기변한 고객 가입 가능,34545원,N,[],Y,Y,Y,"[{'pmProductId': 'PD00000018', 'legacyProductI...",[],"[{'pmProductId': 'PB00001593', 'legacyProductI...","[{'groupName': 'ITM0000215', 'groupList': [{'p...","[{'pmProductId': 'PB00001253', 'legacyProductI...",[],"[{'pmProductId': 'PB00001250', 'legacyProductI...",[],5,1,None,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20%,"[영상통화, 부가통화]",None,"[{'productId': 'BA00000047', 'productName': 'W..."

In [178]:
renamed_valid_meta.to_csv('step_1.csv',index=False, encoding='utf-8-sig')